### ISSUE TITLE
Setup CI github actions to run eslint 

### ISSUE THREAD

**Issue by kalex375** [kalex375/game-queue#19]
Setup CI github actions to run eslint before PR to main branch

example
```
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: npm run lint
```
